/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.businessdevelop.pocguieventos.view;

import com.businessdevelop.pocguieventos.controller.IServicioEvento;
import com.businessdevelop.pocguieventos.controller.ServicioEvento;
import com.businessdevelop.pocguieventos.model.EventoCultural;
import com.businessdevelop.pocguieventos.model.EventoDeportivo;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author mariaramos
 */
public class GUIPrincipal extends javax.swing.JFrame {
    
    private IServicioEvento servicioEvento = new ServicioEvento();


    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
        setTitle("Sistema Gestion de Eventos");
        setLocationRelativeTo(null);
        
        // Opcional: Crear eventos de prueba
        servicioEvento.createEvento(new EventoDeportivo("E001","Futbol","Bogota",50,LocalDate.parse("2026-11-28"),100000, "Futbol", "Liga Colombia"));
        servicioEvento.createEvento(new EventoCultural("C001","Concierto","Ibague",30,LocalDate.parse("2025-10-10"), 80000, "Musical", "Andres Cepeda"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuEvento = new javax.swing.JMenu();
        jMenuCreate = new javax.swing.JMenu();
        jMenuCreateED = new javax.swing.JMenuItem();
        jMenuCreateEC = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuListED = new javax.swing.JMenuItem();
        jMenuListEC = new javax.swing.JMenuItem();
        jMenuItemSearchEvento = new javax.swing.JMenuItem();
        jMenuItemDeleteEvento = new javax.swing.JMenuItem();
        jMenuItemCalcularE = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemAcercaDe = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar3.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar3.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuArchivo.setText("Archivo");

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemExit);

        jMenuBar1.add(jMenuArchivo);

        jMenuEvento.setText("Evento");

        jMenuCreate.setText("Crear");

        jMenuCreateED.setText("Evento Deportivo");
        jMenuCreateED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCreateEDActionPerformed(evt);
            }
        });
        jMenuCreate.add(jMenuCreateED);

        jMenuCreateEC.setText("Evento Cultural");
        jMenuCreateEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCreateECActionPerformed(evt);
            }
        });
        jMenuCreate.add(jMenuCreateEC);

        jMenuEvento.add(jMenuCreate);

        jMenu5.setText("Listar");

        jMenuListED.setText("Evento Deportivo");
        jMenuListED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListEDActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuListED);

        jMenuListEC.setText("Evento Cultural");
        jMenuListEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListECActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuListEC);

        jMenuEvento.add(jMenu5);

        jMenuItemSearchEvento.setText("Buscar");
        jMenuItemSearchEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSearchEventoActionPerformed(evt);
            }
        });
        jMenuEvento.add(jMenuItemSearchEvento);

        jMenuItemDeleteEvento.setText("Eliminar");
        jMenuItemDeleteEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteEventoActionPerformed(evt);
            }
        });
        jMenuEvento.add(jMenuItemDeleteEvento);

        jMenuItemCalcularE.setText("Calcular ");
        jMenuItemCalcularE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCalcularEActionPerformed(evt);
            }
        });
        jMenuEvento.add(jMenuItemCalcularE);

        jMenuBar1.add(jMenuEvento);

        jMenuAyuda.setText("Ayuda");

        jMenuItemAcercaDe.setText("Acerca de...");
        jMenuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercaDeActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItemAcercaDe);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercaDeActionPerformed
            JOptionPane.showMessageDialog(
            this,
            "Desarrollado por:\n\n"
            + " - Gileny Silva Leal, 2220221010\n"
            + " - Jonathan David Moya Patarroyo, 2220222039\n"
            + " - Mauricio Arturo Cañas Medina, 2220211010\n"
            + " - Maria Paula Ramos Carrillo, 2220211032\n",
            "Acerca de",
            JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_jMenuItemAcercaDeActionPerformed

    private GUISearchEvento guiSearchEvento;
    private void jMenuItemSearchEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSearchEventoActionPerformed
        if (guiSearchEvento == null) {
            guiSearchEvento = new GUISearchEvento(servicioEvento);
            }
         guiSearchEvento.setVisible(true);
       
    }//GEN-LAST:event_jMenuItemSearchEventoActionPerformed

    private GUIDeleteEvento guiDeleteEvento;
    
    private void jMenuItemDeleteEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteEventoActionPerformed
        if (guiDeleteEvento == null) {
        guiDeleteEvento = new GUIDeleteEvento(servicioEvento);
        }

        // Intentamos pasar el último buscado si existe
        if (guiSearchEvento != null) {
            guiDeleteEvento.setUltimoIDBuscado(guiSearchEvento.getUltimoIDBuscado());
        }

        guiDeleteEvento.setVisible(true);
    }//GEN-LAST:event_jMenuItemDeleteEventoActionPerformed

    private void jMenuItemCalcularEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCalcularEActionPerformed
        GUICalcularEvento gui = new GUICalcularEvento(servicioEvento);
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemCalcularEActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        this.dispose();

    // Si ya no hay más ventanas abiertas, cierra la aplicación
        if (javax.swing.JFrame.getFrames().length == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuCreateEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCreateEDActionPerformed
        GUICreateED gui = new GUICreateED(servicioEvento);
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuCreateEDActionPerformed

    private void jMenuCreateECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCreateECActionPerformed
        GUICreateEC gui = new GUICreateEC(servicioEvento);
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuCreateECActionPerformed

    private void jMenuListEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListEDActionPerformed
        GUIListED gui = new GUIListED(servicioEvento);
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuListEDActionPerformed

    private void jMenuListECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListECActionPerformed
        GUIListEC gui = new GUIListEC(servicioEvento);
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuListECActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenu jMenuCreate;
    private javax.swing.JMenuItem jMenuCreateEC;
    private javax.swing.JMenuItem jMenuCreateED;
    private javax.swing.JMenu jMenuEvento;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAcercaDe;
    private javax.swing.JMenuItem jMenuItemCalcularE;
    private javax.swing.JMenuItem jMenuItemDeleteEvento;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemSearchEvento;
    private javax.swing.JMenuItem jMenuListEC;
    private javax.swing.JMenuItem jMenuListED;
    // End of variables declaration//GEN-END:variables
}
